#server:
#  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
    #        default_schema: crud

  datasource:
    url: jdbc:postgresql://dpg-cmd5h3ud3nmc73dgv2tg-a.frankfurt-postgres.render.com:5432/snapgramdb
    username: root
    password: ddFKkNUpjVEFHrmtr4t2oNlough2KlKF

  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  credentials:
    access-key: YOURKACCESSEY
    secret-key: YOURSECRETKEY
  region: eu-west-3
  s3:
    buckets:
      customer: 228-connect-market-2